from __future__ import annotations

from typing import Any

from .a_share_matches_tweet_notes import get_project_tweet_note


_THEME_ACCENTS: dict[str, dict[str, str]] = {
    "光模块 / CPO / 光子器件": {
        "accent": "#7dd3fc",
        "accent_soft": "rgba(125, 211, 252, 0.12)",
        "accent_line": "rgba(125, 211, 252, 0.28)",
    },
    "光子材料 / 衬底 / 外延 / SOI": {
        "accent": "#a78bfa",
        "accent_soft": "rgba(167, 139, 250, 0.12)",
        "accent_line": "rgba(167, 139, 250, 0.28)",
    },
    "AI互连 / 连接芯片 / AEC": {
        "accent": "#38bdf8",
        "accent_soft": "rgba(56, 189, 248, 0.12)",
        "accent_line": "rgba(56, 189, 248, 0.28)",
    },
    "存储 / SSD / Memory Cycle": {
        "accent": "#fb7185",
        "accent_soft": "rgba(251, 113, 133, 0.12)",
        "accent_line": "rgba(251, 113, 133, 0.28)",
    },
    "Neocloud / 算力租赁 / GPU供给": {
        "accent": "#22d3ee",
        "accent_soft": "rgba(34, 211, 238, 0.12)",
        "accent_line": "rgba(34, 211, 238, 0.28)",
    },
    "晶圆代工 / Specialty Foundry": {
        "accent": "#f59e0b",
        "accent_soft": "rgba(245, 158, 11, 0.12)",
        "accent_line": "rgba(245, 158, 11, 0.28)",
    },
    "先进封装 / HBM / 玻璃基板": {
        "accent": "#f97316",
        "accent_soft": "rgba(249, 115, 22, 0.12)",
        "accent_line": "rgba(249, 115, 22, 0.28)",
    },
    "商业航天": {
        "accent": "#34d399",
        "accent_soft": "rgba(52, 211, 153, 0.12)",
        "accent_line": "rgba(52, 211, 153, 0.28)",
    },
    "电力 / 电网 / Power Bottleneck": {
        "accent": "#fde047",
        "accent_soft": "rgba(253, 224, 71, 0.12)",
        "accent_line": "rgba(253, 224, 71, 0.28)",
    },
    "关键矿物 / 战略材料": {
        "accent": "#c084fc",
        "accent_soft": "rgba(192, 132, 252, 0.12)",
        "accent_line": "rgba(192, 132, 252, 0.28)",
    },
}


_PROJECT_STOCK_REASON_DATA: dict[str, dict[str, Any]] = {
    "SIVE": {
        "serenity_reason_summary": "Serenity 看 SIVE，不是把它当普通通信股，而是把它放在激光与 CPO 上游 choke point 的位置。核心吸引力在于它更靠近外部光源、laser 与 photonics 链条的上游约束，市场却常常还没把这种上游稀缺性完全 price in。若 CPO 与高密度光互连继续推进，SIVE 的价值更像“卡位资源”而不是单纯景气 beta。",
        "serenity_reason_highlights": ["laser / CPO 上游卡位", "更像 choke point 而非模组受益", "市场定价往往慢于技术路径变化"],
        "tweet_detail_label": "查看推荐脉络",
    },
    "LITE": {
        "serenity_reason_summary": "Serenity 看 LITE，重点通常不是传统光模块叙事，而是它在光器件、CPO 与 photonics 平台能力上的承接。它既能受益于 AI 光互连放量，又有平台型器件公司的属性，因此更适合作为产业平台观察标的。推荐逻辑偏向“谁能稳定承接下一代光互连平台”，而不是短期模组出货。",
        "serenity_reason_highlights": ["光器件平台能力", "CPO 承接者", "AI 光互连平台化受益"],
        "tweet_detail_label": "查看推荐脉络",
    },
    "AAOI": {
        "serenity_reason_summary": "Serenity 对 AAOI 的关注更偏向激光链条、光引擎和 transceiver 的交叉位置，而不只是高速模组行情。它的吸引力在于处在 AI 光互连的关键过渡层，既能看激光器件，又能看模块产品化。真正的推荐理由通常是它可能在技术路径切换时获得重新定价，而不是单纯跟涨。",
        "serenity_reason_highlights": ["激光 + transceiver 双重属性", "AI 光互连过渡层", "可能受益于重新定价"],
        "tweet_detail_label": "查看推荐脉络",
    },
    "COHR": {
        "serenity_reason_summary": "Serenity 看 COHR，核心在激光、光器件和 datacom photonics 的平台地位。它不是最纯的单点瓶颈公司，但在关键器件与光学平台上的积累，使它能承接 AI 光互连主线里的多种需求。推荐理由更多来自它在器件平台与上游能力上的厚度，而不是单一产品景气。",
        "serenity_reason_highlights": ["激光与光器件平台", "datacom photonics 受益", "多产品线承接 AI 光学需求"],
        "tweet_detail_label": "查看推荐脉络",
    },
    "POET": {
        "serenity_reason_summary": "Serenity 看 POET，重点通常放在 external light source、optical engine 和 photonic integration 的新方案价值。它吸引人的地方是技术路径新、市场关注度还没完全扩散，同时又卡在 CPO 与光引擎方案的关键节点。推荐逻辑更像“押注技术路线和平台渗透”，而不是传统成熟器件公司的稳态估值。",
        "serenity_reason_highlights": ["external light source 方案", "optical engine / 光电集成", "新技术路径带来的重估"],
        "tweet_detail_label": "查看推荐脉络",
    },
    "AXTI": {
        "serenity_reason_summary": "Serenity 看 AXTI，明显是按上游材料和 InP / III-V 衬底链来看的。真正吸引力在于它处在化合物半导体和 photonics 的基底层，属于产业要往上做时绕不开的上游材料。推荐理由不是短期主题热度，而是材料 choke point 和供给位置。",
        "serenity_reason_highlights": ["InP / III-V 上游材料", "化合物半导体基底层", "材料 choke point"],
        "tweet_detail_label": "查看推荐脉络",
    },
    "IQE": {
        "serenity_reason_summary": "Serenity 看 IQE，通常是把它放在 epiwafer 和 compound semiconductor upstream 的位置。它的价值在于处在外延片和上游材料层，离最终产品远，却更接近真正难替代的制造前段。推荐理由偏向“上游验证后弹性大、市场理解却滞后”。",
        "serenity_reason_highlights": ["epiwafer / 外延片上游", "compound semiconductor upstream", "市场理解常慢于产业验证"],
        "tweet_detail_label": "查看推荐脉络",
    },
    "SOI": {
        "serenity_reason_summary": "Serenity 看 Soitec，最核心的是它在 SOI 衬底和高端基底上的稀缺地位。它更像基础材料平台而不是终端器件公司，因此推荐逻辑来自 supply chain choke point 和高端基底垄断属性。只要硅光、射频和先进器件继续推进，Soitec 的地位就会不断被验证。",
        "serenity_reason_highlights": ["SOI 衬底稀缺性", "高端基底平台", "硅光与先进器件的底层受益者"],
        "tweet_detail_label": "查看推荐脉络",
    },
    "ALAB": {
        "serenity_reason_summary": "Serenity 看 Astera Labs，核心不是泛 AI 概念，而是它在 CXL、PCIe retimer、switch 和 AI 服务器互连层的协议卡位。它属于真正受益于 AI 系统复杂度提升的连接芯片层，而不是简单拼算力资本开支。推荐理由更偏底层互连标准升级和架构复杂化。",
        "serenity_reason_highlights": ["CXL / PCIe 互连卡位", "AI 服务器连接芯片", "受益于系统架构复杂化"],
        "tweet_detail_label": "查看推荐脉络",
    },
    "CRDO": {
        "serenity_reason_summary": "Serenity 看 Credo，重点在 AEC、铜连接和高速互连链条，而不是泛网络设备叙事。它吸引人的地方是站在 AI 互连升级的基础设施层，直接受益于更高带宽和更复杂布线需求。推荐理由通常来自底层连接标准变化，而不是单纯交换机景气。",
        "serenity_reason_highlights": ["AEC / 铜连接", "高速互连升级", "基础设施层标准变化受益"],
        "tweet_detail_label": "查看推荐脉络",
    },
    "SNDK": {
        "serenity_reason_summary": "Serenity 看 SanDisk，主要是在看 NAND 重定价和 memory cycle，而不是把它当普通消费电子存储股。吸引力在于存储价格拐点一旦确认，经营杠杆和周期弹性会非常直接。推荐逻辑更偏周期错配和库存出清后的重估。",
        "serenity_reason_highlights": ["NAND 重定价", "memory cycle 修复", "库存出清后的周期重估"],
        "tweet_detail_label": "查看推荐脉络",
    },
    "NBIS": {
        "serenity_reason_summary": "Serenity 看 Nebius，更像是在看 neocloud 与 AI 基础设施供给缺口，而不是普通云计算故事。它的关键在于谁能承接真实 GPU 需求、交付算力资源并形成平台能力。推荐理由偏向供给侧稀缺与算力租赁平台化，而不是单纯 IDC 扩产。",
        "serenity_reason_highlights": ["neocloud 供给缺口", "GPU 资源平台化", "供给侧稀缺性"],
        "tweet_detail_label": "查看推荐脉络",
    },
    "TSM": {
        "serenity_reason_summary": "Serenity 看 TSM，是把它视为 AI 半导体最核心的 foundry 锚。它不是一个普通制造股，而是先进逻辑、产能配置、工艺领导力和 AI 资本开支的共同交汇点。推荐理由更多来自“它是整个产业链最关键的产能中枢”。",
        "serenity_reason_highlights": ["AI 半导体 foundry 锚", "先进逻辑产能中枢", "工艺领导力决定产业节奏"],
        "tweet_detail_label": "查看推荐脉络",
    },
    "TSEM": {
        "serenity_reason_summary": "Serenity 看 Tower，更偏特色工艺、模拟、功率和 photonics foundry，而不是先进逻辑。它的价值在于处在一些高附加值但不显眼的制造环节，市场通常不如看 TSM 那样热，但这类特色工艺更容易出现错配。推荐逻辑偏向 niche foundry 的稳定卡位。",
        "serenity_reason_highlights": ["specialty foundry", "模拟 / 功率 / photonics 工艺", "niche 制造卡位"],
        "tweet_detail_label": "查看推荐脉络",
    },
    "XFAB": {
        "serenity_reason_summary": "Serenity 看 X-Fab，主要是在看 silicon photonics 和 specialty foundry 的交叉价值。它不是最热门的名字，但可能处在更细分、更难替代的制造位置。推荐理由来自特色工艺与硅光需求的长期耦合，而不是单纯看晶圆代工景气。",
        "serenity_reason_highlights": ["silicon photonics foundry", "specialty 工艺", "细分制造位置更难替代"],
        "tweet_detail_label": "查看推荐脉络",
    },
    "TOWA": {
        "serenity_reason_summary": "Serenity 看 TOWA，更像在看先进封装和 HBM 设备链，而不是一般半导体设备 beta。关键点在于先进封装工艺正在成为 AI 时代新的瓶颈，封装设备的重要性被明显抬升。推荐理由来自“封装正在接近前道制造的重要性”。",
        "serenity_reason_highlights": ["先进封装 / HBM 设备", "封装成为新瓶颈", "AI 时代后段工艺重要性抬升"],
        "tweet_detail_label": "查看推荐脉络",
    },
    "LPK": {
        "serenity_reason_summary": "Serenity 看 LPK thesis，通常是把它当成玻璃基板和先进封装新材料方向的前瞻下注。吸引力不在现有体量，而在于如果封装路线切到玻璃基板，相关材料和设备链会被整体重估。推荐理由偏向技术路线变化带来的期权价值。",
        "serenity_reason_highlights": ["玻璃基板 thesis", "先进封装新材料", "技术路线切换的期权价值"],
        "tweet_detail_label": "查看推荐脉络",
    },
    "RKLB": {
        "serenity_reason_summary": "Serenity 看 Rocket Lab，重点是它在商业航天里兼具发射、系统和平台延展的能力。它不是纯火箭题材，而更像 SpaceX 之外最值得跟踪的系统级玩家之一。推荐理由来自它可能在商业航天生态中持续抬升的位置，而不是单次发射新闻。",
        "serenity_reason_highlights": ["商业航天系统级玩家", "发射 + 平台能力", "非单次事件驱动"],
        "tweet_detail_label": "查看推荐脉络",
    },
    "-": {
        "serenity_reason_summary": "Serenity 关注 SpaceX，不是因为它是热门私营公司，而是因为它代表了发射、卫星互联网和系统集成的最高标准。它更多是整个商业航天链的锚定参照物，用来反推谁能接近其生态与能力。推荐理由本质上是“定义行业边界的公司”。",
        "serenity_reason_highlights": ["商业航天锚定参照物", "发射 + 星链 + 系统集成", "定义行业边界"],
        "tweet_detail_label": "查看推荐脉络",
    },
    "XLU": {
        "serenity_reason_summary": "Serenity 看 XLU，不是传统公用事业防御逻辑，而是把它放到 AI power bottleneck 里看。随着 AI 数据中心耗电提升，电网投资、输配电升级和公用事业 capex 都可能进入新的周期。推荐理由偏向“电力是 AI 时代的真实瓶颈之一”。",
        "serenity_reason_highlights": ["AI power bottleneck", "电网升级", "公用事业 capex 新周期"],
        "tweet_detail_label": "查看推荐脉络",
    },
    "VNP": {
        "serenity_reason_summary": "Serenity 看 5N Plus，核心是关键矿物、战略材料与供应链安全，而不是普通有色资源故事。它的吸引力来自材料自主可控、关键元素供给和高端工业链需求的重合。推荐理由更偏向战略地位与上游资源卡位。",
        "serenity_reason_highlights": ["关键矿物 / 战略材料", "供应链安全", "上游资源卡位"],
        "tweet_detail_label": "查看推荐脉络",
    },
}


def _fit_level(score: int) -> str:
    if score >= 18:
        return "高"
    if score >= 14:
        return "中高"
    if score >= 10:
        return "中"
    return "观察"


def _match(
    *,
    code: str,
    name: str,
    role: str,
    score: int,
    supply_chain_position: str,
    mapping_path: str,
    judgement: str,
    major_risk: str,
) -> dict[str, Any]:
    return {
        "code": code,
        "name": name,
        "display_name": f"{code} {name}",
        "role": role,
        "serenity_fit_score": score,
        "serenity_fit_level": _fit_level(score),
        "supply_chain_position": supply_chain_position,
        "mapping_path": mapping_path,
        "judgement": judgement,
        "major_risk": major_risk,
    }


def _stock(
    *,
    symbol: str,
    display_name: str,
    company_name: str,
    exchange: str,
    market: str,
    isin: str,
    numeric_code: str,
    theme_chip: str,
    research_summary: str,
    main_matches: list[dict[str, Any]],
    candidate_matches: list[dict[str, Any]],
) -> dict[str, Any]:
    reason_data = _PROJECT_STOCK_REASON_DATA.get(symbol, {})
    note = get_project_tweet_note(symbol)
    return {
        "symbol": symbol,
        "display_name": display_name,
        "company_name": company_name,
        "exchange": exchange,
        "market": market,
        "isin": isin,
        "numeric_code": numeric_code,
        "theme_chip": theme_chip,
        "research_summary": research_summary,
        "serenity_reason_summary": reason_data.get("serenity_reason_summary", research_summary),
        "serenity_reason_highlights": reason_data.get("serenity_reason_highlights", []),
        "tweet_detail_label": reason_data.get("tweet_detail_label", "查看推荐脉络"),
        "stage_snapshot": {
            "name": str((note.get("stage_view") or {}).get("name") or ""),
            "next_step": str((note.get("stage_view") or {}).get("next_step") or ""),
        },
        "market_cap_snapshot": {
            "current_anchor": str((note.get("market_cap_view") or {}).get("current_anchor") or ""),
            "top_scenario": str((((note.get("market_cap_view") or {}).get("scenarios") or [{}])[-1]).get("market_cap") or ""),
        },
        "main_matches": main_matches,
        "candidate_matches": candidate_matches,
    }


def _theme(title: str, project_stocks: list[dict[str, Any]]) -> dict[str, Any]:
    theme_style = _THEME_ACCENTS.get(
        title,
        {
            "accent": "#7dd3fc",
            "accent_soft": "rgba(125, 211, 252, 0.12)",
            "accent_line": "rgba(125, 211, 252, 0.28)",
        },
    )
    return {
        "title": title,
        "slug": title.replace(" / ", "-").replace(" ", "").replace("/", "-"),
        "accent": theme_style["accent"],
        "accent_soft": theme_style["accent_soft"],
        "accent_line": theme_style["accent_line"],
        "project_stocks": project_stocks,
        "project_stock_count": len(project_stocks),
    }


_THEMES: list[dict[str, Any]] = [
    _theme(
        "光模块 / CPO / 光子器件",
        [
            _stock(
                symbol="SIVE",
                display_name="Sivers Semiconductors",
                company_name="Sivers Semiconductors AB",
                exchange="OMXSTO",
                market="Sweden/US",
                isin="SE0003917798",
                numeric_code="-",
                theme_chip="Photonics / laser bottleneck / CPO upstream",
                research_summary="更像 Serenity 原始审美的 photonics 上游名字，应优先映射到光芯片、激光与微光学这些更靠近 choke point 的环节，而不是仅映射高速模组受益股。",
                main_matches=[
                    _match(
                        code="688498",
                        name="源杰科技",
                        role="CW/EML光芯片",
                        score=18,
                        supply_chain_position="上游光芯片",
                        mapping_path="SIVE -> laser / CPO upstream -> A股光芯片",
                        judgement="更接近 Serenity 偏好的上游核心器件 choke point，逻辑强于单纯模组受益。",
                        major_risk="下游 CPO 放量节奏若偏慢，业绩兑现与估值切换会后移。",
                    ),
                    _match(
                        code="688167",
                        name="炬光科技",
                        role="微光学/CPO相关",
                        score=15,
                        supply_chain_position="微光学 / 激光相关",
                        mapping_path="SIVE -> 激光链路 -> 微光学环节",
                        judgement="有 Serenity 风格，但需继续验证其在量产链条中是否属于真正难替代的关键段。",
                        major_risk="若更多停留在相关配套而非核心卡位，分数会向中高回落。",
                    ),
                ],
                candidate_matches=[
                    _match(
                        code="688313",
                        name="仕佳光子",
                        role="AWG/CW/FAU",
                        score=14,
                        supply_chain_position="耦合与无源器件",
                        mapping_path="SIVE -> 光连接 / 耦合器件 -> A股配套",
                        judgement="强相关但更像关键受益环节，未必是最核心的 Serenity choke point。",
                        major_risk="产品位置偏配套，若客户结构变化则弹性不如上游光芯片。",
                    ),
                    _match(
                        code="300394",
                        name="天孚通信",
                        role="FAU/光引擎/CPO器件",
                        score=13,
                        supply_chain_position="光引擎 / 器件平台",
                        mapping_path="SIVE -> CPO器件 / 光引擎 -> A股受益层",
                        judgement="高质量受益股，但在 Serenity 框架下更偏收益层，不是最上游卡位层。",
                        major_risk="市场认知度已高，若新平台放量不超预期，估值继续抬升会受限。",
                    ),
                ],
            ),
            _stock(
                symbol="LITE",
                display_name="Lumentum",
                company_name="Lumentum Holdings Inc.",
                exchange="NASDAQ",
                market="US",
                isin="US55024U1097",
                numeric_code="-",
                theme_chip="CPO / optical components / photonics platform",
                research_summary="平台型 photonics 龙头适合映射到 A 股中的器件平台和少数光芯片能力股，但需要把最上游器件与纯模组区分开。",
                main_matches=[
                    _match(
                        code="300394",
                        name="天孚通信",
                        role="CPO器件/光引擎",
                        score=16,
                        supply_chain_position="器件平台 / 光引擎",
                        mapping_path="LITE -> CPO器件平台 -> A股器件平台",
                        judgement="平台属性最接近，能承接 Lumentum 在光器件与 CPO 平台上的映射逻辑。",
                        major_risk="平台型业务覆盖广，若 CPO 占比提升不及预期，纯 Serenity 叙事浓度会下降。",
                    ),
                    _match(
                        code="002281",
                        name="光迅科技",
                        role="光芯片+光模块",
                        score=15,
                        supply_chain_position="器件到模块一体化",
                        mapping_path="LITE -> 光芯片 / 光器件平台 -> A股一体化平台",
                        judgement="比纯模组更接近 LITE 的全栈属性，但仍带有较强平台型国企特征。",
                        major_risk="业务面较宽，若市场转向追逐更纯粹的上游卡位，弹性可能弱于细分龙头。",
                    ),
                ],
                candidate_matches=[
                    _match(
                        code="300308",
                        name="中际旭创",
                        role="高速光模块",
                        score=12,
                        supply_chain_position="高速光模块",
                        mapping_path="LITE -> 光模块平台 -> A股高速模组",
                        judgement="是核心受益龙头，但更偏下游模组环节，不是最典型 Serenity 上游映射。",
                        major_risk="市场已充分认知 AI 光模块主线，预期差主要来自景气持续性。",
                    ),
                    _match(
                        code="300502",
                        name="新易盛",
                        role="高速光模块",
                        score=12,
                        supply_chain_position="高速光模块",
                        mapping_path="LITE -> 光模块平台 -> A股高速模组",
                        judgement="受益逻辑清楚，但更适合作为候选池而非主映射。",
                        major_risk="若下游需求波动，模组价格与出货节奏对业绩影响更直接。",
                    ),
                ],
            ),
            _stock(
                symbol="AAOI",
                display_name="Applied Optoelectronics",
                company_name="Applied Optoelectronics, Inc.",
                exchange="NASDAQ",
                market="US",
                isin="US03823U1025",
                numeric_code="-",
                theme_chip="Optical transceivers / lasers / AI photonics",
                research_summary="AAOI 兼具 transceiver 与激光链条特征，A 股映射宜突出器件与光引擎，而不是把全部权重放到高速模组本身。",
                main_matches=[
                    _match(
                        code="300394",
                        name="天孚通信",
                        role="FAU/光引擎/CPO器件",
                        score=16,
                        supply_chain_position="光引擎 / 核心器件",
                        mapping_path="AAOI -> 激光 / 光引擎 -> A股器件平台",
                        judgement="最能承接 AAOI 在激光与器件平台之间的桥梁属性。",
                        major_risk="若 AI 光互连需求阶段性回落，器件弹性也会同步收敛。",
                    ),
                    _match(
                        code="002281",
                        name="光迅科技",
                        role="光芯片+光模块",
                        score=15,
                        supply_chain_position="一体化光通信平台",
                        mapping_path="AAOI -> transceiver / laser platform -> A股一体化平台",
                        judgement="在 A 股里属于更完整的平台映射，但气质仍弱于纯上游卡位。",
                        major_risk="平台型属性会稀释单一 AI 光互连的弹性。",
                    ),
                ],
                candidate_matches=[
                    _match(
                        code="300308",
                        name="中际旭创",
                        role="高速光模块",
                        score=12,
                        supply_chain_position="高速光模块",
                        mapping_path="AAOI -> 光模块 -> A股模组龙头",
                        judgement="强受益但更偏景气跟随，不是 Serenity 最偏好的上游定位。",
                        major_risk="估值与订单节奏对市场预期敏感度较高。",
                    ),
                    _match(
                        code="300502",
                        name="新易盛",
                        role="高速光模块",
                        score=12,
                        supply_chain_position="高速光模块",
                        mapping_path="AAOI -> 光模块 -> A股模组龙头",
                        judgement="属于同主线高弹性标的，但更像候选池受益层。",
                        major_risk="模组价格竞争与客户结构变化会放大业绩波动。",
                    ),
                ],
            ),
            _stock(
                symbol="COHR",
                display_name="Coherent",
                company_name="Coherent Corp.",
                exchange="NYSE",
                market="US",
                isin="US19247G1076",
                numeric_code="-",
                theme_chip="Lasers / optical components / datacom photonics",
                research_summary="Coherent 的核心是激光与光器件平台，映射时应优先找能承接激光器、核心器件与平台能力的 A 股，而不是只找高速模组。",
                main_matches=[
                    _match(
                        code="300394",
                        name="天孚通信",
                        role="光器件/CPO器件平台",
                        score=16,
                        supply_chain_position="器件平台",
                        mapping_path="COHR -> 激光 / 光器件平台 -> A股器件平台",
                        judgement="平台属性和多品类光器件定位最接近，是更合理的主映射。",
                        major_risk="若市场继续追逐更纯器件 choke point，平台股溢价可能落后。",
                    ),
                    _match(
                        code="002281",
                        name="光迅科技",
                        role="光芯片+光器件平台",
                        score=15,
                        supply_chain_position="光器件 / 光芯片平台",
                        mapping_path="COHR -> 光器件平台 -> A股一体化光器件",
                        judgement="更像平台映射而非单点瓶颈映射，适合作为共同主映射。",
                        major_risk="传统通信链业务占比仍会影响 AI 主线纯度。",
                    ),
                ],
                candidate_matches=[
                    _match(
                        code="300308",
                        name="中际旭创",
                        role="高速光模块平台",
                        score=12,
                        supply_chain_position="高速光模块",
                        mapping_path="COHR -> datacom photonics -> A股模组龙头",
                        judgement="更多是受益层映射，适合放在候选池而不是主映射。",
                        major_risk="模组景气变化会比器件平台更快传导到估值。",
                    ),
                ],
            ),
            _stock(
                symbol="POET",
                display_name="POET Technologies",
                company_name="POET Technologies Inc.",
                exchange="NASDAQ",
                market="US/Canada",
                isin="CA73044W1041",
                numeric_code="-",
                theme_chip="Optical engines / external light source / photonic integration",
                research_summary="POET 更强调外部光源与光引擎集成，A 股映射应围绕光引擎、耦合器件和光芯片链条展开，而不是只对应泛光模块。",
                main_matches=[
                    _match(
                        code="300394",
                        name="天孚通信",
                        role="光引擎/FAU/CPO器件",
                        score=17,
                        supply_chain_position="光引擎 / 耦合器件",
                        mapping_path="POET -> optical engine / external light source -> A股光引擎",
                        judgement="最贴近 POET 的光引擎与器件整合路线，适合放在主映射首位。",
                        major_risk="若相关平台导入不及预期，市场会重新回到传统光器件估值框架。",
                    ),
                    _match(
                        code="688498",
                        name="源杰科技",
                        role="CW/EML光芯片",
                        score=16,
                        supply_chain_position="上游光芯片",
                        mapping_path="POET -> external light source -> A股光芯片",
                        judgement="比模组更接近外部光源和核心光芯片逻辑，符合 Serenity 的上游偏好。",
                        major_risk="若平台方案没有明确拉动上游光芯片需求，映射强度会下降。",
                    ),
                ],
                candidate_matches=[
                    _match(
                        code="688313",
                        name="仕佳光子",
                        role="AWG/CW/FAU",
                        score=14,
                        supply_chain_position="耦合器件 / 无源器件",
                        mapping_path="POET -> 光引擎配套 -> A股耦合器件",
                        judgement="相关性强，但更偏配套层，适合作为候选池补充。",
                        major_risk="若导入节奏偏慢，配套环节弹性通常不及上游光芯片。",
                    ),
                ],
            ),
        ],
    ),
    _theme(
        "光子材料 / 衬底 / 外延 / SOI",
        [
            _stock(
                symbol="AXTI",
                display_name="AXT Inc",
                company_name="AXT, Inc.",
                exchange="NASDAQ",
                market="US",
                isin="US00246W1036",
                numeric_code="-",
                theme_chip="InP substrate / compound semiconductor materials",
                research_summary="AXT 属于更标准的上游材料链映射，应该优先寻找衬底、III-V 材料和光芯片材料这些 A 股上的材料 choke point。",
                main_matches=[
                    _match(
                        code="600703",
                        name="三安光电",
                        role="III-V化合物半导体/光芯片",
                        score=16,
                        supply_chain_position="化合物半导体材料到器件",
                        mapping_path="AXTI -> InP / III-V materials -> A股化合物半导体平台",
                        judgement="既承接材料逻辑，又具备器件延展性，是更完整的主映射。",
                        major_risk="平台业务较宽，若市场只追逐纯材料端，溢价不一定最陡。",
                    ),
                    _match(
                        code="002428",
                        name="云南锗业",
                        role="锗材料/化合物半导体材料",
                        score=15,
                        supply_chain_position="关键上游材料",
                        mapping_path="AXTI -> compound semiconductor materials -> A股锗与材料链",
                        judgement="更纯上游材料逻辑，符合 Serenity 对资源与材料 choke point 的偏好。",
                        major_risk="产业兑现更依赖下游化合物半导体扩产和良率提升。",
                    ),
                ],
                candidate_matches=[
                    _match(
                        code="002222",
                        name="福晶科技",
                        role="激光与光学晶体材料",
                        score=12,
                        supply_chain_position="光学晶体材料",
                        mapping_path="AXTI -> 光子材料 -> A股晶体材料",
                        judgement="相关但不是最直接的 InP / III-V 映射，更适合候选池。",
                        major_risk="材料方向更偏激光晶体，和 AXT 的复合半导体主线不完全一致。",
                    ),
                ],
            ),
            _stock(
                symbol="IQE",
                display_name="IQE",
                company_name="IQE plc",
                exchange="LSE",
                market="UK",
                isin="GB0009619924",
                numeric_code="-",
                theme_chip="Epiwafer / compound semiconductor upstream",
                research_summary="IQE 的核心是 epiwafer 和化合物半导体上游，映射时应优先外延与上游材料，而不是泛 LED 或普通封装。",
                main_matches=[
                    _match(
                        code="600703",
                        name="三安光电",
                        role="化合物半导体外延/芯片",
                        score=17,
                        supply_chain_position="外延片 / 化合物半导体平台",
                        mapping_path="IQE -> epiwafer / compound semiconductor -> A股外延与芯片平台",
                        judgement="在 A 股中最接近外延片和化合物半导体量产平台，是自然的主映射。",
                        major_risk="若市场把其视为传统 LED 平台，Serenity 风格溢价会受限。",
                    ),
                    _match(
                        code="002428",
                        name="云南锗业",
                        role="化合物半导体材料",
                        score=15,
                        supply_chain_position="关键上游材料",
                        mapping_path="IQE -> 外延上游材料 -> A股材料端",
                        judgement="更纯上游材料链，具备 Serenity 喜欢的材料稀缺属性。",
                        major_risk="对下游导入节奏较敏感，且市场预期常受资源价格扰动。",
                    ),
                ],
                candidate_matches=[
                    _match(
                        code="300323",
                        name="华灿光电",
                        role="LED/化合物半导体外延",
                        score=12,
                        supply_chain_position="外延与器件",
                        mapping_path="IQE -> 外延片 -> A股外延平台",
                        judgement="方向相关，但业务纯度和 Serenity 叙事一致性弱于主映射。",
                        major_risk="更多受常规 LED 与传统景气影响，AI 光子属性不够纯。",
                    ),
                ],
            ),
            _stock(
                symbol="SOI",
                display_name="Soitec",
                company_name="Soitec",
                exchange="EPA",
                market="France",
                isin="FR0013227113",
                numeric_code="-",
                theme_chip="SOI substrates / silicon photonics substrate monopoly",
                research_summary="Soitec 典型对应高端基底与 SOI 衬底垄断逻辑，主映射应优先放在 SOI / 高端硅片，而不是泛半导体材料。",
                main_matches=[
                    _match(
                        code="688126",
                        name="沪硅产业",
                        role="半导体硅片/SOI材料",
                        score=18,
                        supply_chain_position="SOI / 高端硅片基底",
                        mapping_path="SOI -> silicon photonics substrate -> A股 SOI 硅片",
                        judgement="是最直接的 A 股 SOI 映射，也最贴近 Serenity 的基底 choke point 审美。",
                        major_risk="高端产品兑现依赖客户验证与良率爬坡，节奏慢于题材交易。",
                    ),
                    _match(
                        code="605358",
                        name="立昂微",
                        role="半导体硅片",
                        score=15,
                        supply_chain_position="高端硅片",
                        mapping_path="SOI -> 高端晶圆基底 -> A股硅片平台",
                        judgement="虽不如沪硅直接，但仍属于高端硅片链的重要承接者。",
                        major_risk="SOI 纯度和直接性弱于主映射第一名。",
                    ),
                ],
                candidate_matches=[
                    _match(
                        code="688233",
                        name="神工股份",
                        role="半导体硅材料",
                        score=12,
                        supply_chain_position="半导体硅材料",
                        mapping_path="SOI -> 高端硅材料 -> A股材料端",
                        judgement="更像基底材料延伸映射，适合作为候选池补充。",
                        major_risk="和 Soitec 的直接 SOI 垄断逻辑相比，映射路径更长。",
                    ),
                ],
            ),
        ],
    ),
    _theme(
        "AI互连 / 连接芯片 / AEC",
        [
            _stock(
                symbol="ALAB",
                display_name="Astera Labs",
                company_name="Astera Labs, Inc.",
                exchange="NASDAQ",
                market="US",
                isin="US04626A1034",
                numeric_code="-",
                theme_chip="AI connectivity / CXL / PCIe retimers and switches",
                research_summary="ALAB 更偏 AI 服务器互连芯片与协议层机会，主映射应优先选择具备互连芯片、交换与接口卡位的 A 股，而不是纯材料受益。",
                main_matches=[
                    _match(
                        code="688008",
                        name="澜起科技",
                        role="内存接口/CXL/服务器互连",
                        score=18,
                        supply_chain_position="接口芯片 / 互连协议层",
                        mapping_path="ALAB -> CXL / memory interconnect -> A股接口芯片",
                        judgement="是最像 Serenity 逻辑的直接芯片卡位，兼具协议壁垒和平台导入属性。",
                        major_risk="若 CXL 商业化节奏低于预期，市场可能重新按传统接口芯片估值。",
                    ),
                    _match(
                        code="688515",
                        name="裕太微-U",
                        role="高速以太网PHY/连接芯片",
                        score=15,
                        supply_chain_position="高速连接芯片",
                        mapping_path="ALAB -> 高速互连 -> A股 PHY / 连接芯片",
                        judgement="更偏单点连接芯片，虽不如澜起全面，但更接近底层互连器件卡位。",
                        major_risk="商业化和客户突破仍需时间，节奏不确定性较高。",
                    ),
                ],
                candidate_matches=[
                    _match(
                        code="688702",
                        name="盛科通信-U",
                        role="交换芯片/数据中心网络",
                        score=14,
                        supply_chain_position="交换芯片 / 网络层",
                        mapping_path="ALAB -> switch / network fabric -> A股交换芯片",
                        judgement="方向一致，但更偏网络交换侧，而非 Astera 最核心的接口和 retimer 逻辑。",
                        major_risk="行业竞争与客户拓展对节奏影响较大。",
                    ),
                ],
            ),
            _stock(
                symbol="CRDO",
                display_name="Credo Technology",
                company_name="Credo Technology Group Holding Ltd",
                exchange="NASDAQ",
                market="US",
                isin="KYG254571055",
                numeric_code="-",
                theme_chip="AEC / copper connectivity / high-speed interconnect",
                research_summary="Credo 更像高速互连与铜连接链条的代表，A 股要优先找高速材料和互连芯片，而不是泛 PCB 跟随股。",
                main_matches=[
                    _match(
                        code="600183",
                        name="生益科技",
                        role="高速覆铜板/高速材料",
                        score=16,
                        supply_chain_position="高速材料",
                        mapping_path="CRDO -> high-speed copper interconnect -> A股高速材料",
                        judgement="更符合 Serenity 对材料 choke point 的偏好，属于上游铲子型映射。",
                        major_risk="材料验证节奏和下游放量节奏之间存在时间差。",
                    ),
                    _match(
                        code="688702",
                        name="盛科通信-U",
                        role="交换芯片/数据中心网络",
                        score=14,
                        supply_chain_position="网络连接芯片",
                        mapping_path="CRDO -> 高速互连 / switch -> A股交换芯片",
                        judgement="更像互连芯片平台的候选主映射，但纯度略弱于上游材料。",
                        major_risk="更多受国产替代节奏驱动，和 Credo 的 AEC 直接性稍弱。",
                    ),
                ],
                candidate_matches=[
                    _match(
                        code="002463",
                        name="沪电股份",
                        role="高速交换机PCB",
                        score=12,
                        supply_chain_position="高速 PCB",
                        mapping_path="CRDO -> 高速互连硬件 -> A股高速 PCB",
                        judgement="清楚的受益链条，但更偏中游承载层，适合候选池。",
                        major_risk="景气度与客户 capex 周期关联更强，壁垒相对弱于材料和芯片。",
                    ),
                ],
            ),
        ],
    ),
    _theme(
        "存储 / NAND / HBM",
        [
            _stock(
                symbol="SNDK",
                display_name="SanDisk",
                company_name="Sandisk Corporation",
                exchange="NASDAQ",
                market="US",
                isin="US80004C2008",
                numeric_code="-",
                theme_chip="NAND repricing / memory cycle",
                research_summary="SanDisk 这条线更偏 NAND 周期与重定价，A 股里应区分真正受价格上行拉动的模组、控制器和设计，而不是把所有存储股平铺。",
                main_matches=[
                    _match(
                        code="688525",
                        name="佰维存储",
                        role="存储器/模组",
                        score=15,
                        supply_chain_position="模组 / 企业级存储",
                        mapping_path="SNDK -> NAND cycle -> A股存储模组与产品化",
                        judgement="更能承接 NAND 周期修复与产品化弹性，是较合理的主映射。",
                        major_risk="模组链条对价格波动和库存周期的敏感度较高。",
                    ),
                    _match(
                        code="001309",
                        name="德明利",
                        role="存储控制器/模组",
                        score=14,
                        supply_chain_position="控制器 / 模组",
                        mapping_path="SNDK -> NAND + controller -> A股控制器与模组",
                        judgement="比单纯模组更具结构性，但稳定性依赖下游客户拓展。",
                        major_risk="价格修复若不持续，控制器与模组的盈利弹性会明显收敛。",
                    ),
                ],
                candidate_matches=[
                    _match(
                        code="301308",
                        name="江波龙",
                        role="存储模组/NAND产业链",
                        score=13,
                        supply_chain_position="模组 / 品牌",
                        mapping_path="SNDK -> NAND cycle -> A股模组品牌",
                        judgement="逻辑顺畅，但市场熟悉度较高，更适合候选池而非主映射。",
                        major_risk="品牌与模组属性决定其受库存周期扰动更大。",
                    ),
                    _match(
                        code="603986",
                        name="兆易创新",
                        role="存储芯片设计",
                        score=12,
                        supply_chain_position="存储芯片设计",
                        mapping_path="SNDK -> memory repricing -> A股存储设计",
                        judgement="更偏泛存储景气映射，不是最直接的 NAND 周期映射。",
                        major_risk="业务结构较宽，SanDisk 的纯 NAND 主线映射并不完全重合。",
                    ),
                ],
            ),
        ],
    ),
    _theme(
        "算力 / 云基础设施 / GPU云",
        [
            _stock(
                symbol="NBIS",
                display_name="Nebius Group",
                company_name="Nebius Group N.V.",
                exchange="NASDAQ",
                market="US",
                isin="NL0009805522",
                numeric_code="-",
                theme_chip="AI cloud / neocloud / AI infrastructure",
                research_summary="Nebius 更偏 neocloud 与算力基础设施，不是最标准的硬科技上游，但可映射到算力基础设施与 IDC 中更具资源与平台能力的 A 股。",
                main_matches=[
                    _match(
                        code="603019",
                        name="中科曙光",
                        role="AI服务器/算力基础设施",
                        score=16,
                        supply_chain_position="算力基础设施平台",
                        mapping_path="NBIS -> neocloud / AI infra -> A股算力平台",
                        judgement="更接近算力平台和基础设施供给侧，而不是单纯 IDC 租赁。",
                        major_risk="算力建设节奏与政策导向会共同影响业绩兑现。",
                    ),
                    _match(
                        code="300738",
                        name="奥飞数据",
                        role="IDC/算力基础设施",
                        score=13,
                        supply_chain_position="IDC / 机柜资源",
                        mapping_path="NBIS -> GPU cloud infra -> A股 IDC 承载层",
                        judgement="属于受益链条中较直接的资源层，但上游 choke point 属性不强。",
                        major_risk="机柜上架与资本开支节奏对业绩影响很大。",
                    ),
                ],
                candidate_matches=[
                    _match(
                        code="000977",
                        name="浪潮信息",
                        role="AI服务器",
                        score=13,
                        supply_chain_position="服务器整机",
                        mapping_path="NBIS -> AI compute deployment -> A股服务器",
                        judgement="更多是算力部署受益股，符合度不如算力平台与资源层。",
                        major_risk="整机属性较强，盈利受客户招标和价格竞争影响更大。",
                    ),
                    _match(
                        code="300383",
                        name="光环新网",
                        role="IDC/云计算基础设施",
                        score=12,
                        supply_chain_position="IDC / 云基础设施",
                        mapping_path="NBIS -> cloud infra -> A股 IDC",
                        judgement="方向相关，但更像传统 IDC 映射，Serenity 风格较弱。",
                        major_risk="传统 IDC 估值框架会压制纯 AI 叙事溢价。",
                    ),
                ],
            ),
        ],
    ),
    _theme(
        "晶圆代工 / 特色工艺",
        [
            _stock(
                symbol="TSM",
                display_name="Taiwan Semiconductor",
                company_name="Taiwan Semiconductor Manufacturing Company Limited",
                exchange="NYSE",
                market="Taiwan",
                isin="US8740391003",
                numeric_code="2330",
                theme_chip="Advanced logic / foundry / AI semiconductor anchor",
                research_summary="TSM 是 AI 半导体锚点，A 股映射应优先找最具平台能力的晶圆代工与特色工艺承接者，而不是泛半导体制造。",
                main_matches=[
                    _match(
                        code="688981",
                        name="中芯国际",
                        role="晶圆代工平台",
                        score=17,
                        supply_chain_position="先进逻辑代工平台",
                        mapping_path="TSM -> foundry anchor -> A股晶圆代工平台",
                        judgement="是最直接的 A 股代工平台映射，虽然先进制程差距仍在，但平台属性最接近。",
                        major_risk="资本开支与制程推进节奏会持续影响估值兑现。",
                    ),
                    _match(
                        code="688347",
                        name="华虹公司",
                        role="特色工艺代工",
                        score=15,
                        supply_chain_position="特色工艺代工",
                        mapping_path="TSM -> specialty / mature foundry -> A股特色工艺",
                        judgement="更偏成熟与特色工艺承接，适合作为共同主映射。",
                        major_risk="AI 主线纯度不如先进逻辑代工，高端逻辑溢价传导有限。",
                    ),
                ],
                candidate_matches=[
                    _match(
                        code="688249",
                        name="晶合集成",
                        role="晶圆代工",
                        score=12,
                        supply_chain_position="晶圆代工",
                        mapping_path="TSM -> foundry ecosystem -> A股晶圆代工",
                        judgement="逻辑成立但平台与先进逻辑代表性弱于前两者。",
                        major_risk="受单一产线结构和景气波动影响更大。",
                    ),
                ],
            ),
            _stock(
                symbol="TSEM",
                display_name="Tower Semiconductor",
                company_name="Tower Semiconductor Ltd.",
                exchange="NASDAQ",
                market="Israel",
                isin="IL0010823792",
                numeric_code="-",
                theme_chip="Specialty foundry / photonics foundry",
                research_summary="Tower 更偏特色工艺、模拟和 photonics foundry，A 股主映射要偏向特色工艺与功率/模拟平台，而不是先进逻辑。",
                main_matches=[
                    _match(
                        code="688347",
                        name="华虹公司",
                        role="特色工艺/功率器件代工",
                        score=17,
                        supply_chain_position="特色工艺代工",
                        mapping_path="TSEM -> specialty foundry -> A股特色工艺代工",
                        judgement="和 Tower 的特色工艺定位最接近，是自然的主映射首选。",
                        major_risk="若市场重新只追逐先进逻辑，特色工艺平台相对收益会变弱。",
                    ),
                    _match(
                        code="688396",
                        name="华润微",
                        role="功率半导体/IDM平台",
                        score=14,
                        supply_chain_position="功率器件 / IDM",
                        mapping_path="TSEM -> analog / power process -> A股功率平台",
                        judgement="更偏功率器件与特色工艺承接，符合 Tower 的成熟工艺审美。",
                        major_risk="IDM 模式会让代工映射的纯度低于华虹。",
                    ),
                ],
                candidate_matches=[
                    _match(
                        code="688981",
                        name="中芯国际",
                        role="晶圆代工平台",
                        score=13,
                        supply_chain_position="代工平台",
                        mapping_path="TSEM -> foundry ecosystem -> A股代工平台",
                        judgement="是平台型补充，但和 Tower 的特色工艺调性并非完全同频。",
                        major_risk="先进逻辑标签更强，会稀释特色工艺映射。",
                    ),
                ],
            ),
            _stock(
                symbol="XFAB",
                display_name="X-Fab",
                company_name="X-FAB Silicon Foundries SE",
                exchange="EPA",
                market="Europe",
                isin="BE0974310428",
                numeric_code="-",
                theme_chip="Silicon photonics / specialty foundry",
                research_summary="X-Fab 兼具特色工艺与硅光 foundry 想象，A 股映射应继续放在特色工艺代工和功率平台，而不是泛设备链。",
                main_matches=[
                    _match(
                        code="688347",
                        name="华虹公司",
                        role="特色工艺代工",
                        score=17,
                        supply_chain_position="特色工艺 / 模拟代工",
                        mapping_path="XFAB -> specialty / silicon photonics foundry -> A股特色工艺",
                        judgement="与 X-Fab 的特色工艺定位高度贴近，且更有平台承接能力。",
                        major_risk="若硅光业务没有持续放量，市场仍可能按成熟制程定价。",
                    ),
                    _match(
                        code="688396",
                        name="华润微",
                        role="功率器件/IDM平台",
                        score=14,
                        supply_chain_position="功率 / 模拟平台",
                        mapping_path="XFAB -> analog / power ecosystem -> A股功率平台",
                        judgement="更偏生态补充映射，适合作为共同主映射。",
                        major_risk="IDM 业务结构和 foundry 纯度存在差异。",
                    ),
                ],
                candidate_matches=[
                    _match(
                        code="688981",
                        name="中芯国际",
                        role="晶圆代工平台",
                        score=13,
                        supply_chain_position="代工平台",
                        mapping_path="XFAB -> foundry ecosystem -> A股代工平台",
                        judgement="平台补充逻辑成立，但特色工艺直接性弱于华虹。",
                        major_risk="估值更多受先进逻辑预期影响，而非 X-Fab 式特色工艺预期。",
                    ),
                ],
            ),
        ],
    ),
    _theme(
        "先进封装 / 玻璃基板 / HBM设备",
        [
            _stock(
                symbol="TOWA",
                display_name="Towa",
                company_name="TOWA CORPORATION",
                exchange="TSE",
                market="Japan",
                isin="JP3555700008",
                numeric_code="6315",
                theme_chip="HBM packaging / advanced packaging equipment",
                research_summary="TOWA 是更典型的先进封装设备映射，A 股主映射要优先找工艺设备与测试设备，而不是只停在封装材料概念。",
                main_matches=[
                    _match(
                        code="688120",
                        name="华海清科",
                        role="先进封装/CMP设备",
                        score=16,
                        supply_chain_position="先进封装关键设备",
                        mapping_path="TOWA -> advanced packaging equipment -> A股工艺设备",
                        judgement="更靠近先进封装核心设备环节，符合 Serenity 对设备 choke point 的偏好。",
                        major_risk="先进封装设备放量仍依赖客户资本开支与验证节奏。",
                    ),
                    _match(
                        code="300604",
                        name="长川科技",
                        role="测试设备/先进封测",
                        score=14,
                        supply_chain_position="测试设备",
                        mapping_path="TOWA -> 封装测试环节 -> A股测试设备",
                        judgement="是封装链条里的关键装备，但更偏测试段，不如前者贴近主工艺设备。",
                        major_risk="订单节奏受行业资本开支波动影响较大。",
                    ),
                ],
                candidate_matches=[
                    _match(
                        code="600520",
                        name="文一科技",
                        role="封装设备",
                        score=13,
                        supply_chain_position="封装设备",
                        mapping_path="TOWA -> 封装设备 -> A股封装装备",
                        judgement="方向对，但平台能力和核心工艺代表性弱于主映射。",
                        major_risk="产品结构与验证壁垒仍需持续强化。",
                    ),
                ],
            ),
            _stock(
                symbol="LPK",
                display_name="LPKF / LPK thesis",
                company_name="LPKF Laser & Electronics SE",
                exchange="XETR",
                market="Europe",
                isin="DE0006450000",
                numeric_code="-",
                theme_chip="Glass substrates / advanced packaging",
                research_summary="这条线更偏玻璃基板和先进封装新材料，A 股映射应优先材料与玻璃基板承接者，而不是泛封装设备。",
                main_matches=[
                    _match(
                        code="603773",
                        name="沃格光电",
                        role="玻璃基板/显示与封装材料",
                        score=16,
                        supply_chain_position="玻璃基板 / 封装材料",
                        mapping_path="LPK thesis -> glass substrate -> A股玻璃基板材料",
                        judgement="是最直接的玻璃基板映射，更接近 Serenity 偏好的新材料 choke point。",
                        major_risk="新场景导入仍处于产业验证阶段，放量节奏有不确定性。",
                    ),
                    _match(
                        code="601208",
                        name="东材科技",
                        role="电子材料/封装材料",
                        score=13,
                        supply_chain_position="封装材料",
                        mapping_path="LPK thesis -> advanced packaging materials -> A股电子材料",
                        judgement="更偏材料承接层，适合作为主映射补充。",
                        major_risk="和玻璃基板的直接性弱于沃格光电。",
                    ),
                ],
                candidate_matches=[
                    _match(
                        code="002106",
                        name="莱宝高科",
                        role="玻璃基材/显示材料",
                        score=12,
                        supply_chain_position="玻璃基材",
                        mapping_path="LPK thesis -> glass-related materials -> A股玻璃材料",
                        judgement="相关性存在，但更多是玻璃材料泛映射，适合作为候选池。",
                        major_risk="与先进封装玻璃基板主线之间仍有较长映射路径。",
                    ),
                ],
            ),
        ],
    ),
    _theme(
        "商业航天 / 卫星 / 发射",
        [
            _stock(
                symbol="RKLB",
                display_name="Rocket Lab",
                company_name="Rocket Lab USA, Inc.",
                exchange="NASDAQ",
                market="US",
                isin="US7731221062",
                numeric_code="-",
                theme_chip="Launch / space systems / SpaceX #2 thesis",
                research_summary="商业航天在 A 股上的纯度不如 AI 硬件链高，需要把真正具备卫星制造和系统能力的标的放前面，其余配套放到候选池。",
                main_matches=[
                    _match(
                        code="600118",
                        name="中国卫星",
                        role="卫星制造/卫星应用",
                        score=15,
                        supply_chain_position="卫星整星 / 系统平台",
                        mapping_path="RKLB -> space systems -> A股卫星系统平台",
                        judgement="在 A 股里最接近卫星系统与整星平台能力，是较合理的主映射。",
                        major_risk="商业化节奏受体制订单与新业务推进共同影响。",
                    ),
                    _match(
                        code="600879",
                        name="航天电子",
                        role="航天电子配套",
                        score=13,
                        supply_chain_position="航天电子配套",
                        mapping_path="RKLB -> 航天电子链条 -> A股配套",
                        judgement="更偏关键配套而非整星平台，适合作为主映射补充。",
                        major_risk="弹性依赖具体配套渗透率，市场想象力弱于整星平台。",
                    ),
                ],
                candidate_matches=[
                    _match(
                        code="300762",
                        name="上海瀚讯",
                        role="卫星通信",
                        score=12,
                        supply_chain_position="卫星通信应用",
                        mapping_path="RKLB -> satellite ecosystem -> A股卫星通信",
                        judgement="属于生态受益层，不是最直接的发射与系统映射。",
                        major_risk="更偏应用和通信侧，和火箭发射主线并不完全同频。",
                    ),
                ],
            ),
            _stock(
                symbol="-",
                display_name="SpaceX",
                company_name="Space Exploration Technologies Corp.",
                exchange="Private",
                market="US",
                isin="-",
                numeric_code="-",
                theme_chip="Space / satellite / launch ecosystem",
                research_summary="Private 主题更适合作为生态映射，不应强行装作可交易可比公司；页面上要明确这是系统级映射而非可比估值映射。",
                main_matches=[
                    _match(
                        code="600118",
                        name="中国卫星",
                        role="卫星制造/卫星应用",
                        score=14,
                        supply_chain_position="卫星系统平台",
                        mapping_path="SpaceX ecosystem -> satellite systems -> A股卫星平台",
                        judgement="更适合作为生态平台映射，而非直接可比映射。",
                        major_risk="SpaceX 的发射、星链和航天系统一体化优势在 A 股中没有完全对位标的。",
                    ),
                    _match(
                        code="600879",
                        name="航天电子",
                        role="航天电子配套",
                        score=12,
                        supply_chain_position="航天电子配套",
                        mapping_path="SpaceX ecosystem -> avionics / subsystems -> A股配套",
                        judgement="偏配套层，不宜给过高 Serenity Fit。",
                        major_risk="更多是题材映射，非真正的系统平台映射。",
                    ),
                ],
                candidate_matches=[
                    _match(
                        code="300762",
                        name="上海瀚讯",
                        role="卫星通信",
                        score=11,
                        supply_chain_position="卫星通信应用",
                        mapping_path="SpaceX ecosystem -> satellite internet -> A股通信应用",
                        judgement="更偏生态受益，适合作为候选池尾部。",
                        major_risk="与发射及航天系统主线距离较远。",
                    ),
                ],
            ),
        ],
    ),
    _theme(
        "电力 / 公用事业 / 电网设备",
        [
            _stock(
                symbol="XLU",
                display_name="Utilities Select Sector SPDR",
                company_name="Utilities Select Sector SPDR Fund",
                exchange="NYSEARCA",
                market="US",
                isin="US81369Y8865",
                numeric_code="-",
                theme_chip="Utilities / AI power bottleneck / grid modernization",
                research_summary="这条线是 Serenity 非常重视的 AI power bottleneck，但 A 股映射应优先找电网自动化和关键设备，而不是泛公用事业。",
                main_matches=[
                    _match(
                        code="600406",
                        name="国电南瑞",
                        role="电网自动化/调度系统",
                        score=17,
                        supply_chain_position="电网自动化 / 调度系统",
                        mapping_path="XLU -> grid modernization -> A股电网自动化",
                        judgement="更接近电网升级中的关键中枢，符合 Serenity 对基础设施 bottleneck 的偏好。",
                        major_risk="电网投资节奏和招标周期会影响兑现速度。",
                    ),
                    _match(
                        code="000400",
                        name="许继电气",
                        role="输配电/电网设备",
                        score=15,
                        supply_chain_position="输配电关键设备",
                        mapping_path="XLU -> power equipment -> A股输配电设备",
                        judgement="比泛电力股更接近设备 choke point，适合作为主映射补充。",
                        major_risk="产品周期更受基建投资节奏影响，弹性低于纯软件中枢。",
                    ),
                ],
                candidate_matches=[
                    _match(
                        code="601179",
                        name="中国西电",
                        role="输变电设备",
                        score=13,
                        supply_chain_position="输变电设备",
                        mapping_path="XLU -> grid capex -> A股输变电设备",
                        judgement="方向正确，但更偏广谱设备供应，不是最核心自动化中枢。",
                        major_risk="设备制造属性使盈利弹性受订单结构影响较大。",
                    ),
                    _match(
                        code="300693",
                        name="盛弘股份",
                        role="电力电子/充储配电",
                        score=12,
                        supply_chain_position="电力电子 / 配电侧",
                        mapping_path="XLU -> power bottleneck -> A股配电与电力电子",
                        judgement="属于受益延伸，不宜放到主映射层。",
                        major_risk="更依赖配电与储能景气，不完全等同电网瓶颈主线。",
                    ),
                ],
            ),
        ],
    ),
    _theme(
        "关键矿物 / 稀土 / 战略材料",
        [
            _stock(
                symbol="VNP",
                display_name="5N Plus",
                company_name="5N Plus Inc.",
                exchange="TSX",
                market="Canada",
                isin="CA33833L1094",
                numeric_code="-",
                theme_chip="Critical minerals / strategic materials sovereignty",
                research_summary="战略材料是 Serenity 方法论里典型的上游 choke point 方向，A 股映射应偏资源与加工一体化，而不是泛有色主题。",
                main_matches=[
                    _match(
                        code="600111",
                        name="北方稀土",
                        role="稀土龙头/战略资源",
                        score=17,
                        supply_chain_position="关键矿物 / 稀土上游",
                        mapping_path="5N Plus -> strategic materials -> A股稀土龙头",
                        judgement="是最直接的战略资源映射，符合 Serenity 对关键矿物上游的偏好。",
                        major_risk="资源价格周期会掩盖产业链战略属性，导致估值波动较大。",
                    ),
                    _match(
                        code="600392",
                        name="盛和资源",
                        role="稀土资源与加工",
                        score=15,
                        supply_chain_position="资源 + 加工",
                        mapping_path="5N Plus -> materials sovereignty -> A股资源加工一体化",
                        judgement="资源与加工一体化更符合关键材料自主可控逻辑。",
                        major_risk="盈利对商品价格弹性较高，产业链战略叙事易被周期噪音覆盖。",
                    ),
                ],
                candidate_matches=[
                    _match(
                        code="600259",
                        name="广晟有色",
                        role="稀土与有色资源",
                        score=14,
                        supply_chain_position="有色资源",
                        mapping_path="5N Plus -> strategic materials -> A股资源平台",
                        judgement="方向一致，但和关键矿物纯主线相比更偏综合资源平台。",
                        major_risk="综合资源属性会降低单一战略材料映射纯度。",
                    ),
                ],
            ),
        ],
    ),
]


def get_a_share_match_catalog() -> dict[str, Any]:
    total_project_stocks = sum(theme["project_stock_count"] for theme in _THEMES)
    return {
        "title": "Serenity推荐股与A股映射表",
        "eyebrow": "Serenity Mapping",
        "description": (
            "基于 Serenity 的上游瓶颈、供应链映射和前瞻错配框架，对项目推荐股做 A 股主映射与候选池重排。"
            " 页面保留行情与 Tweets 研究能力，同时把原有静态标签升级为可比较的 Serenity Fit 评分卡。"
        ),
        "theme_count": len(_THEMES),
        "project_stock_count": total_project_stocks,
        "themes": _THEMES,
    }
